service: my-guys

image: kamal/my-guys

servers:
  web:
    - 64.227.47.10

proxy:
  ssl: true
  hosts:
    - myguysburgers.com
  healthcheck:
    interval: 3
    path: /up
    timeout: 3

registry:
  server: registry.digitalocean.com/ok-boring
  username: kamal-skiff

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "/var/wild-willy/db:/rails/sqlite"

asset_path: /rails/public/assets

builder:
  arch: amd64
